### ISSUE TITLE
Lack of validation on emails from agencia-cliente 

### ISSUE THREAD

**Issue by Ruben35** [Ruben35/TROBIFY-IPN#2]
Falta validar que no se pueda registrar un correo que **_ya este en la tabla de agencia o en la tabla de cliente_**. 

Endpoints que necesitan revisión:
- `auth/registro`
- `agencia/registrar`

**Comment by catzin** [comment]
El endpoint de registro  ya esta funcionando, pruebalo con el mismo caso con el que detectaste el error xdd

**Comment by Cesar269** [comment]
Endpoint de la agencia para el token ya esta.
